#!/bin/bash

# Identifiy the default gateway in the routing table
netstat -rn | grep "default" | grep "en0" | awk '{print $2}'

# netstat is a command-line network utility that displays network connections 
# for Transmission Control Protocol, routing tables, and a number of network 
# interface and network protocol statistics.