#!/bin/bash

# Q5 - Identify the IP address of the DNS that responds to the following url: slash16.org
nslookup slash16.org | grep "Server" | awk '{print $2}'

# http://osxdaily.com/2011/06/03/get-dns-server-ip-command-line-mac-os-x/

# "#53" indicates that we are communicating with it on port 53, 
# which is the standard port number domain name servers use to accept queries