#!/bin/bash

#Q21 - List all real users on the VM

#Human users have UIDs starting at 1000, so you can use that fact to filter out the non-humans:
#This cuts the first (username) and third (UID) colon-delimited fields from /etc/passwd, 
#then filters for the resulting lines which end with a colon and four digits, 
#then cuts the first (username) field from that, leaving you with a list of users with UIDs between
#1000 and 9999.

awk -F: '$3 >= 1000 && $1 != "nobody" {print $1}' /etc/passwd

#this filters out the 'nobody' user

#https://askubuntu.com/questions/257421/list-all-human-users