#!/bin/bash

# Q23- Explain how connect yourself as new user. (With graphic session and ssh session)

echo "We need to use the command su (switch user)"
echo "su -l username"
echo "The -l option makes changes the current directory to the user repo "
echo "Then enter the password of the user."

# https://linuxize.com/post/su-command-in-linux/

echo "From the mac terminal: ssh -p 2222 user@localhost"