#!/bin/bash

# Write a script which displays only the login, UID and Path of each entry of the /etc/passwd file
# https://www.cyberciti.biz/faq/understanding-etcpasswd-file-format/

awk -F: '{print $1 " " $3 " " $6} ' /etc/passwd

# to filter 'real' users: awk -F: '$3 >= 1000 && $1 != "nobody" {print $1 " " $3 " " $6} ' /etc/passwd)
