#!/bin/bash

# Write a script which delete an ACTIVE user on the VM.
# https://unix.stackexchange.com/questions/126507/bash-script-to-remove-user
# https://linuxacademy.com/blog/linux/conditions-in-bash-scripting-if-statements/#string-based-conditions

## Use the userdel command to remove the old user: userdel 'user's username'
## You can also delete that user's home directory and mail spool by using 
## the -r flag with the command: userdel -r "user's username"

user_exists=$(getent passwd $1)

if [ $# -ne 1 ]; then
    echo "usage: ./02 <username>"
    exit 0
fi

if [ $(awk -F: '$3 >= 1000 && $1 != "nobody" {print $1 " " $3 " " $6} ' /etc/passwd | grep $1 | wc -c) -eq 0 ]
then
    echo "User $1 does not exist or You are not allowed"
    exit 0
fi

if [ -z "$user_exists" ] 
then
        echo "User $1 does not exist"
else
        read -p "Do you want to delete User $1? (y/n)" -n 1 prompt
        if [ "$prompt" == "y" ];
        then
            sudo userdel -r "$1" > /dev/null 2>&1
            echo ""
            echo "User $1 deleted"
        elif [ "$prompt" == "n" ];
        then
            echo ""
            echo "OK"
        else
            echo ""
            echo "Invalid choice"
        fi
fi
 